name: CI/CD on creating a new tag

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Install Angular
        run: npm install -g @angular/cli

      - name: Build
        run: ng build --prod --base-href="https://sanjitkhan.github.io/angular-trading-app/"

      - name: Archive dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact
          path: dist

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact
          path: dist

      - name: Deploy
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: dist/angular-trading-app
          branch: gh-pages
          token: ${{ secrets.ANGULAR_TRADING_APP_ACCESS_TOKEN }}
          